### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by alikamr** [blopa/Magento-Messenger-Chat#2]
Hi, 
I am trying to install your extension on Magento 2.2.2 but after installation I cannot access Stores > Configuration. Gives me the following error:

1 exception(s):
Exception #0 (Exception): Notice: Undefined index: id in /home/admin/web/anayaonline.com/public_html/vendor/magento/module-config/Model/Config/Structure/Element/Iterator.php on line 63

Exception #0 (Exception): Notice: Undefined index: id in /home/admin/web/anayaonline.com/public_html/vendor/magento/module-config/Model/Config/Structure/Element/Iterator.php on line 63
#0 /home/admin/web/anayaonline.com/public_html/vendor/magento/module-config/Model/Config/Structure/Element/Iterator.php(63): Magento\Framework\App\ErrorHandler->handler(8, 'Undefined index...', '/home/admin/web...', 63, Array)
#1 /home/admin/web/anayaonline.com/public_html/vendor/magento/module-config/Model/Config/Structure.php(146): Magento\Config\Model\Config\Structure\Element\Iterator->setElements(Array, 'default')
#2 /home/admin/web/anayaonline.com/public_html/generated/code/Magento/Config/Model/Config/Structure/Interceptor.php(24): Magento\Config\Model\Config\Structure->getTabs()
#3 /home/admin/web/anayaonline.com/public_html/vendor/magento/module-config/Model/Config/Structure.php(209): Magento\Config\Model\Config\Structure\Interceptor->getTabs()
#4 /home/admin/web/anayaonline.com/public_html/generated/code/Magento/Config/Model/Config/Structure/Interceptor.php(76): Magento\Config\Model\Config\Structure->getFirstSection()
#5 /home/admin/web/anayaonline.com/public_html/vendor/magento/module-config/Controller/Adminhtml/System/AbstractConfig.php(60): Magento\Config\Model\Config\Structure\Interceptor->getFirstSection()
#6 /home/admin/web/anayaonline.com/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Config\Controller\Adminhtml\System\AbstractConfig->dispatch(Object(Magento\Framework\App\Request\Http))
#7 /home/admin/web/anayaonline.com/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Config\Controller\Adminhtml\System\Config\Index\Interceptor->___callParent('dispatch', Array)
#8 /home/admin/web/anayaonline.com/public_html/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Config\Controller\Adminhtml\System\Config\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#9 /home/admin/web/anayaonline.com/public_html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Config\Controller\Adminhtml\System\Config\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#10 /home/admin/web/anayaonline.com/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Config\Controller\Adminhtml\System\Config\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#11 /home/admin/web/anayaonline.com/public_html/generated/code/Magento/Config/Controller/Adminhtml/System/Config/Index/Interceptor.php(39): Magento\Config\Controller\Adminhtml\System\Config\Index\Interceptor->___callPlugins('dispatch', Array, NULL)
#12 /home/admin/web/anayaonline.com/public_html/vendor/magento/framework/App/FrontController.php(55): Magento\Config\Controller\Adminhtml\System\Config\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#13 /home/admin/web/anayaonline.com/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#14 /home/admin/web/anayaonline.com/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#15 /home/admin/web/anayaonline.com/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#16 /home/admin/web/anayaonline.com/public_html/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#17 /home/admin/web/anayaonline.com/public_html/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#18 /home/admin/web/anayaonline.com/public_html/generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\Framework\App\Http->launch()
#19 /home/admin/web/anayaonline.com/public_html/vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http\Interceptor->launch()
#20 /home/admin/web/anayaonline.com/public_html/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#21 {main}

**Comment by blopa** [comment]
Hi there. Thanks for reporting this issue. Could you try again and send us the log that's on your var/log folder?

**Comment by blopa** [comment]
Did you got it working?

**Comment by alikamr** [comment]
HI, Apologies for the late response. No I did not manage to install it. The first installation corrupted by whole Magento 2.2.2 installation so I have to install Magento from scratch. I will try again after installing magento again.

**Comment by NudeWeb** [comment]
Got the same issue on 2.2.2 is there a fix for this?

**Comment by blopa** [comment]
@NudeWeb could you please send me your log files?

**Comment by blopa** [comment]
Try running

`php bin/magento cache:flush;php bin/magento cache:clean;php bin/magento setup:upgrade;php bin/magento setup:static-content:deploy -f`

**Comment by Migno** [comment]
Good day, ive just tried to install it on a Magento 2.2.5 - Got the same error, if you need something specific to fix it feel free to contact me. Im kinda scared to uninstall it after the comment from @alikamr

**Comment by alikamr** [comment]
@Migno I gave up on it because Facebook's own solution takes 2 mins to install. 

https://developers.facebook.com/docs/messenger-platform/discovery/customer-chat-plugin

**Comment by Migno** [comment]
@alikamr saw that to late - as i said, im kinda scared to uninstall it now :D Since ive installed it on a live store without checking before.

But thanks buddy, ill give that a try

**Comment by alikamr** [comment]
@Migno I had to restore my backup. My suggestion is to restore the backup because the store didn't work and I had to fix it because I did it on a live store as well.

**Comment by Migno** [comment]
@alikamr I've managed to uninstall it without doing a restore of a backup.
Do you mind telling me how you integrated the official Facebook Chat ?

**Comment by alikamr** [comment]
@Migno Its quite simple. Just go to page settings then messenger platform. You will see the option of Messenger Chat Plugin. Set it up and then paste the code into your website. The code needs to be pasted in the body tag that you will find it in the footer section under design.

**Comment by CesarChris710** [comment]
Hi, Pls update to magento 2.2.5
